### ISSUE TITLE
Unable to open file (in target "CometChatPro-swift-sampleApp" in project "CometChatPro-swift-sampleApp") (in target 'CometChatPro-swift-sampleApp')

### ISSUE THREAD

**Issue by kittlsk** [cometchat-pro-samples/ios-swift-chat-app#1]
Hi,

I'm xCode newbie.  I tried to download the project and run it in xCode but prompted the below the error.  Seems like it's looking for Pods directory under the Pods.  Anyone else has this issue?

Showing Recent Messages
/ios-swift-chat-app-master/Pods/Pods/Target Support Files/Pods-CometChatPro-swift-sampleApp/Pods-CometChatPro-swift-sampleApp.debug.xcconfig: unable to open file (in target "CometChatPro-swift-sampleApp" in project "CometChatPro-swift-sampleApp") (in target 'CometChatPro-swift-sampleApp')

**Comment by pushpsenairekar2911** [comment]
Hello kittlsk , 

Kindly,  Navigate to Project --> Targets --> **Build settings** --> **Objective - C Bridging Header.**

Change the below path:
_/Users/admin1/Documents/CometChat Pro/PrivateRepo/cometchat-pro-ios-ui/ios-swift-chat-app/CometChatPro-swift-sampleApp/Resources/CometChatPro-Bridging-Header.h_

To: **_CometChatPro-swift-sampleApp/Resources/CometChatPro-Bridging-Header.h_**

This should resolve your issue. We will fix this in our upcoming  release.

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,
Pushpsen A.
CometChatPro Team

**Comment by kittlsk** [comment]
Hi Pushpsen,

I did exactly what you suggested, clean and build, still the same problem prompted:


Showing Recent Messages
:-1: /Users/kittlee/Desktop/ios-swift-chat-app-master/Pods/Pods/Target Support Files/Pods-CometChatPro-swift-sampleApp/Pods-CometChatPro-swift-sampleApp.debug.xcconfig: unable to open file (in target "CometChatPro-swift-sampleApp" in project "CometChatPro-swift-sampleApp") (in target 'CometChatPro-swift-sampleApp')

**Comment by pushpsenairekar2911** [comment]
Hello kittlsk,

We have released the new version for ios-swift-chat-app-master. Kindly, clone the fresh repository from https://github.com/cometchat-pro-samples/ios-swift-chat-app/. After cloning, kindly use 'pod install' command to install the required pods. 

Once done, build the project. This should resolve your issue.

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,
Pushpsen A.
CometChatPro Team

**Comment by kittlsk** [comment]
Hi @pushpsenairekar2911 ,

I deleted the project folder and cloned the new one.  After installing pods and building, still the same issue prompted:


Showing Recent Messages
/Users/kittlee/Desktop/ios-swift-chat-app-master/Pods/Pods/Target Support Files/Pods-CometChatPro-swift-sampleApp/Pods-CometChatPro-swift-sampleApp.debug.xcconfig: unable to open file (in target "CometChatPro-swift-sampleApp" in project "CometChatPro-swift-sampleApp") (in target 'CometChatPro-swift-sampleApp')

**Comment by pushpsenairekar2911** [comment]
Hello kittlsk, 

Hope your day is going well. You can [refer this link](https://github.com/cometchat-pro-samples/ios-swift-chat-app/blob/master/troubleshoot.md) to resolve this issue. 

Hope this helps.

**Comment by pushpsenairekar2911** [comment]
We are closing this ticket. You can re-open this ticket if anything needed.
